### ISSUE TITLE
Recommendation: Add custom configuratio-LOL

### ISSUE THREAD

**Issue by QianMuu** [MrGenie151/Ender-Dragon-Fight-Remastered#22] opened 2024-04-06 18:41 UTC
Maybe I can customize the ender dragon's health and rewards.
This mod is pretty cool and I look forward to adding more attacks if you have the time.

**Comment by rcubedev** [comment] 2024-08-27 05:22
Duplicate of #3

**Closed** 2024-08-27 05:22 UTC
