### ISSUE TITLE
FR: Add config

### ISSUE THREAD

**Issue by cookienogood** [MrGenie151/Ender-Dragon-Fight-Remastered#32] opened 2024-08-02 17:30 UTC
Hello i was wondering if it was possible to add a config. I believe that the dragon should do even more damage/have more health and I was wondering if we could have control in determining how much it should have.

**Comment by rcubedev** [comment] 2024-08-27 05:11
Duplicate of #22

**Comment by rcubedev** [comment] 2024-08-27 05:18
Oops...

**Closed** 2024-08-27 05:18 UTC
Labels: duplicate, enhancement
