### ISSUE TITLE
anvil attack bugged

### ISSUE THREAD

**Issue by dxcently** [MrGenie151/Ender-Dragon-Fight-Remastered#13] opened 2023-09-22 00:28 UTC
The anvil attack is bugged, and it's still procing even after I killed the ender dragon, and in overworld

**Comment by dxcently** [comment] 2023-09-22 00:29
id also add that it still persist after resetting server

**Comment by dxcently** [comment] 2023-09-22 00:39
sorry, another thing to add. i just noticed that the ender zombies for some reason are also spawning the overworld?

**Comment by rcubedev** [comment] 2024-08-27 05:54
The anvil attack executing in overworld/nether should be fixed in v4.2 (275baa).

If the dragon is killed while the anvil attack is ongoing, the anvil will still drop out of the sky. This will be fixed when the anvil attack is swapped (see #12).

**Comment by rcubedev** [comment] 2024-08-27 05:58
End Zombies in overworld is likely caused by End Zombies entering the return portal and ending up at spawn.

**Closed** 2024-08-27 05:58 UTC
